# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 劉夏陽
subtitle: Yahellow，小窝被发现了。
author: 刘夏阳
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com/liuxiayang.github.io      # Note: don't forget to modify the CNAME file to your url
root: /
#permalink: :year/:month/:day/:title/
permalink: :category/:title/
permalink_defaults:
  lang: en

#Custom Setting Start

# Site settings
SEOTitle: 刘夏阳 | Blog
email: e-mail_address
description: "liuxiayang blog"
keyword: ""
header-img: https://github.com/liuxiayang/pic/blob/master/wallpaper/Firework.jpg?raw=true
article-img: /img/article_header/article_bg.jpg
404-img: /img/header_img/404.png
signature: false #show signature
signature-img: img/signature/BeanTechSign-white.png


# SNS settings
# RSS: false
# weibo_username:     Demonbaneen
# zhihu_username:     Demonbane
github_username: liuxiayang
# twitter_username:   Demonbane_x
# facebook_username:  xxx
# linkedin_username:  xxx

# Build settings
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`


# Disqus settings
#disqus_username: your-disqus-ID

# Duoshuo settings
# duoshuo_username: kaijun
# Share component is depend on Comment so we can NOT use share only.
#duoshuo_share: true                     # set to false if you want to use Comment without Sharing


# Analytics settings
#Baidu Analytics
ba_track_id: xxx
# Google Analytics
ga_track_id: 'UA-XXXXXXXX-X'          # Format: UA-xxxxxx-xx
ga_domain: yoursite


# Sidebar settings
sidebar: true                       # whether or not using Sidebar.
sidebar-about-description: "世界变变变变变更好"
sidebar-avatar: /img/avatar/Hikigaya.Hachiman.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`
widgets:
- featured-tags
- short-about
- recent-posts
- friends-blog
- archive
#- category

# widget behavior
## Archive
archives-img: /img/header_img/archives-widget.jpg
archive_type: 'monthly'
show_count: true


## Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


## Friends
friends: [
    {
      title: "有不少，广告位。",
      href: ""
    },
    {
      title: "两块包月，过时不候。",
      href: ""
    },
    {
      title: "现在是，赞助时间。",
      href: ""
    },
    {
      title: "以后火了，可别后悔。",
      href: ""
    },
]

#Custom Setting End

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: in-article
category_map:
  Docker: docker
  Kubernetes: kubernetes
  Golang: golang
  Nginx: nginx
  Etcd: etcd
  Database: database

tag_map:
home_posts_tag: true # show posts tags

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
display_updated: true

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: archives

archive_generator:
  per_page: 10
  yearly: true
  monthly: true
  daily: false
  
# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  
# Extensions
## Plugins: https://hexo.io/plugins/

# recommended-posts
# reference: https://github.com/huiwang/hexo-recommended-posts
# recommended_posts:
#   server: https://api.truelaurel.com #后端推荐服务器地址
#   timeoutInMillis: 10000 #服务时长，超过此时长，则使用离线推荐模式
#   internalLinks: 3 #内部文章数量
#   externalLinks: 0 #外部文章数量
#   autoDisplay: true, #自动在文章底部显示推荐文章
#   titleHtml: <h2>推荐文章<span style="font-size:0.45em; color:gray"></span></h2> #自定义标题

# hexo-tag-aplayer
# reference: https://github.com/MoePlayer/hexo-tag-aplayer
# aplayer:
#   meting: true

# MeingJS support for Aplayer
# reference: https://github.com/metowolf/MetingJS & https://github.com/MoePlayer/APlayer
metingjs: false
data-id: 2423410161
data-server: netease  
data-type: playlist
data-fixed: true
  # data-mini:
  # data-autoplay:    

# Reward
reward: false
reward_comment: 赞赏一下
wechatpay: wechatpay_url
alipay: alipay_url

# Share
# Reference: https://github.com/overtrue/share.js
share: true

# Reference: https://github.com/YuyingWu/hexo-generator-index-plus
index_generator_plus:
  path: ''
  per_page: 10

## Themes: https://hexo.io/themes/
theme: huweihuang

#sitemap
sitemap:
  path: sitemap.xml

# Deployment
## Docs: https://hexo.io/docs/deployment.html
# repository: https://github.com/huweihuang/xxxxxxx.github.io.git
# branch: master
deploy:
  type: git
  repository: https://github.com/liuxiayang/liuxiayang.github.io
  branch: master

#live2d
live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  debug: false
  model:
    use: live2d-widget-model-tororo
  display:
    position: left
    width: 150
    height: 300
  mobile:
    show: true

# visitors count
counter: true
